name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # runs gradle build tast without tests
      - name: Build with Gradle
        run: ./gradlew build -x test
      
      # builds fat jar file with gradle's dependencies
      - name: Archive Jar with Dependencies
        uses: actions/upload-artifact@v2
        with:
          name: Jar with Dependencies
          path: build/libs
          
  test: 
    runs-on: ubuntu-latest
    needs: build
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it   
      - uses: actions/checkout@v2
 
      # Runs gradle test task
      - name: Test with Gradle
        run: ./gradlew test --tests "*"
        
      # builds zip file with jUnit tests  
      - name: Archive test report
        uses: actions/upload-artifact@v2
        with:
          name: Test report
          path: build/reports/tests/test
             
      # build zip file with Junit tests coverage  
      - name: Archive coverage report
        uses: actions/upload-artifact@v2
        with:
          name: Code Coverage report
          path: build/reports/jacoco/test/html
          
          
  documentation: 
    runs-on: ubuntu-latest
    needs: test
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it 
      - uses: actions/checkout@v2
      
      # runs dokkaHtml
      - name: Dokka with Gradle
        run: ./gradlew dokkaHtml
      
      # builds zip file with kdoc website inside
      - name: Archive KDoc Documentation
        uses: actions/upload-artifact@v2
        with:
          name: KDoc Documentation Site
          path: build/dokka/html
