# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs gradle's test task
      - name: test with gradle
        run: ./gradlew test --tests "*"
      
      # builds zip file with JUnit tests report inside
      - name: archive test report
        uses: actions/upload-artifact@v2
        with: 
          name: test report
          path: build/reports/tests/test
          
      # builds a zip file with JUnit code coverage report inside
      - name: archive coverage report
        uses: actions/upload-artifact@v2
        with:
          name: code coverage report
          path: builds/reports/jacoco/test/html
      
      
        
      # builds fat jar file with gradle's dependencies
      - name: archive jar with dependencies
        uses: actions/upload-artifact@v2
        with:
         name: jar with dependencies
         path: build/libs

     
